inherit_from:
    - .rubocop_airbnb.yml


Metrics/LineLength:
  Enabled: false

Airbnb/ModuleMethodInWrongFile:
  Description: Define a module method in the file that defines the module, not a file that
    happens to use the module as a namespace.
  Enabled: false
  Include:
    - 'app/**/*'
    - 'lib/**/*'

#ここにはrubocopでコード解析したくないファイルやフォルダを指定します
AllCops:
    Exclude:
        - 'db/**/*'
        - 'bin/*'
        - 'config/environments/*'
        - 'config/application.rb'
        - 'config/initializers/*'
        - 'config/spring.rb'
        - 'lib/tasks/*'
        - 'vendor/**/*'
        - 'path/ruby'
        - 'spec/**/*'